CREATE DATABASE tsherpa;

USE tsherpa;

CREATE TABLE ROLE(
	role_id INT PRIMARY KEY AUTO_INCREMENT,
	role VARCHAR(255) DEFAULT NULL
);

CREATE TABLE user(
	user_id INT PRIMARY KEY AUTO_INCREMENT,
	active INT DEFAULT 0, 
	login_id VARCHAR(255) NOT NULL,
	user_name VARCHAR(255) NOT NULL,
	password VARCHAR(300) NOT NULL
);

CREATE TABLE user_role(
	user_id INT NOT NULL,
	role_id INT NOT NULL,
	PRIMARY KEY (user_id, role_id)
);


CREATE TABLE notice(
	no INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(300) NOT NULL,
	content VARCHAR(1000) NOT NULL,
	author INT,
	regdate DATETIME DEFAULT CURRENT_TIME,
	cnt INT DEFAULT 0,
	FOREIGN KEY(author) REFERENCES user(user_id) ON DELETE CASCADE
);

SHOW TABLES;